
ques1a: ques1a.c
	gcc -o ques1a ques1a.c

ques1b: ques1b.c
	gcc -o ques1b ques1b.c

ques2a: ques2a.c
	gcc -o ques2a ques2a.c

ques2b: ques2b.c
	gcc -o ques2b ques2b.c

ques2cstacks: ques2cstacks.c
	gcc -o ques2cstacks ques2ctacks.c

ques2cqueues: quescqueues.c
	gcc -o ques2cqueues ques2cqueues.c

ques3: ques3.c 
	gcc -o ques3 ques3.c -lm

ques5: ques5.c
	gcc -o ques5 ques5.c